/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RomanizedLyricsRouteImport } from './routes/romanized-lyrics'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ApiRomanizeRouteImport } from './routes/api/romanize'
import { Route as ApiSongsRouteImport } from './routes/api/songs'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as EditSongIdRouteImport } from './routes/edit.$songId'
import { Route as PlayerSongIdRouteImport } from './routes/player.$songId'
import { Route as ProcessingSongIdRouteImport } from './routes/processing.$songId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RomanizedLyricsRoute = RomanizedLyricsRouteImport.update({
  id: '/romanized-lyrics',
  path: '/romanized-lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRomanizeRoute = ApiRomanizeRouteImport.update({
  id: '/api/romanize',
  path: '/api/romanize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSongsRoute = ApiSongsRouteImport.update({
  id: '/api/songs',
  path: '/api/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const EditSongIdRoute = EditSongIdRouteImport.update({
  id: '/edit/$songId',
  path: '/edit/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSongIdRoute = PlayerSongIdRouteImport.update({
  id: '/player/$songId',
  path: '/player/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingSongIdRoute = ProcessingSongIdRouteImport.update({
  id: '/processing/$songId',
  path: '/processing/$songId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/romanized-lyrics': typeof RomanizedLyricsRoute
  '/upload': typeof UploadRoute
  '/api/romanize': typeof ApiRomanizeRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/edit/$songId': typeof EditSongIdRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/romanized-lyrics': typeof RomanizedLyricsRoute
  '/upload': typeof UploadRoute
  '/api/romanize': typeof ApiRomanizeRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/edit/$songId': typeof EditSongIdRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/romanized-lyrics': typeof RomanizedLyricsRoute
  '/upload': typeof UploadRoute
  '/api/romanize': typeof ApiRomanizeRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/edit/$songId': typeof EditSongIdRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/romanized-lyrics'
    | '/upload'
    | '/api/romanize'
    | '/api/songs'
    | '/api/transcribe'
    | '/api/translate'
    | '/edit/$songId'
    | '/player/$songId'
    | '/processing/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/romanized-lyrics'
    | '/upload'
    | '/api/romanize'
    | '/api/songs'
    | '/api/transcribe'
    | '/api/translate'
    | '/edit/$songId'
    | '/player/$songId'
    | '/processing/$songId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/romanized-lyrics'
    | '/upload'
    | '/api/romanize'
    | '/api/songs'
    | '/api/transcribe'
    | '/api/translate'
    | '/edit/$songId'
    | '/player/$songId'
    | '/processing/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  RomanizedLyricsRoute: typeof RomanizedLyricsRoute
  UploadRoute: typeof UploadRoute
  ApiRomanizeRoute: typeof ApiRomanizeRoute
  ApiSongsRoute: typeof ApiSongsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  EditSongIdRoute: typeof EditSongIdRoute
  PlayerSongIdRoute: typeof PlayerSongIdRoute
  ProcessingSongIdRoute: typeof ProcessingSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romanized-lyrics': {
      id: '/romanized-lyrics'
      path: '/romanized-lyrics'
      fullPath: '/romanized-lyrics'
      preLoaderRoute: typeof RomanizedLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/romanize': {
      id: '/api/romanize'
      path: '/api/romanize'
      fullPath: '/api/romanize'
      preLoaderRoute: typeof ApiRomanizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/songs': {
      id: '/api/songs'
      path: '/api/songs'
      fullPath: '/api/songs'
      preLoaderRoute: typeof ApiSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$songId': {
      id: '/edit/$songId'
      path: '/edit/$songId'
      fullPath: '/edit/$songId'
      preLoaderRoute: typeof EditSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$songId': {
      id: '/player/$songId'
      path: '/player/$songId'
      fullPath: '/player/$songId'
      preLoaderRoute: typeof PlayerSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$songId': {
      id: '/processing/$songId'
      path: '/processing/$songId'
      fullPath: '/processing/$songId'
      preLoaderRoute: typeof ProcessingSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  RomanizedLyricsRoute: RomanizedLyricsRoute,
  UploadRoute: UploadRoute,
  ApiRomanizeRoute: ApiRomanizeRoute,
  ApiSongsRoute: ApiSongsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  EditSongIdRoute: EditSongIdRoute,
  PlayerSongIdRoute: PlayerSongIdRoute,
  ProcessingSongIdRoute: ProcessingSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
