/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as PlayerSongIdRouteImport } from './routes/player.$songId'
import { Route as ProcessingSongIdRouteImport } from './routes/processing.$songId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSongIdRoute = PlayerSongIdRouteImport.update({
  id: '/player/$songId',
  path: '/player/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingSongIdRoute = ProcessingSongIdRouteImport.update({
  id: '/processing/$songId',
  path: '/processing/$songId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/player/$songId': typeof PlayerSongIdRoute
  '/processing/$songId': typeof ProcessingSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/api/transcribe'
    | '/player/$songId'
    | '/processing/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/api/transcribe'
    | '/player/$songId'
    | '/processing/$songId'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/api/transcribe'
    | '/player/$songId'
    | '/processing/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  PlayerSongIdRoute: typeof PlayerSongIdRoute
  ProcessingSongIdRoute: typeof ProcessingSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$songId': {
      id: '/player/$songId'
      path: '/player/$songId'
      fullPath: '/player/$songId'
      preLoaderRoute: typeof PlayerSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$songId': {
      id: '/processing/$songId'
      path: '/processing/$songId'
      fullPath: '/processing/$songId'
      preLoaderRoute: typeof ProcessingSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  PlayerSongIdRoute: PlayerSongIdRoute,
  ProcessingSongIdRoute: ProcessingSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
